title: config
env: string
port: integer
serviceName: string
sqlDatabase:
  host: string
  port: integer
  database: string
  username: string
  password: string
  connectionLimit: integer
  migrations:
    type: array
    items: string
  entities:
    type: array
    items: string
  replicas:
    type: array
    items: 
      host: string
      port: integer
      username: string
      password: string
      database: string
redis:
  host: string
  port: integer
commonRedis:
  host: string
  port: integer
rabbit:
  uri: string
crons:
  eachClusterCron: boolean
  globalCron: boolean
  transactionProcessor: boolean
disabledConsumers:
  newUser: boolean
apis:
  github:
    url: string
    clientId: string
    webhookSecret: string
    apiKey: string
    privateKey: string