version: '3.4'
services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
  commonredis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6380:6379
    environment:
      - REDIS_REPLICATION_MODE=master
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbit
    volumes:
      - ./tools/rabbit/config/definitions.json:/etc/rabbitmq/definitions.json
      - ./tools/rabbit/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./tools/rabbit/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./tools/rabbit/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
  mysql:
    image: mysql:latest
    ports:
      - 3324:3306
    environment:
      - MYSQL_DATABASE=x-bounty-app-db
      - MYSQL_ROOT_PASSWORD=root